### ISSUE TITLE
Improve CSRF token generating approach

### ISSUE THREAD

**Issue by peter279k** [selective-php/csrf#9]
As title, the current CSRF token generating approach is as follows:

- Set salt and default is empty string.
- Set session id.
- Using the `hash` to do `sha-256` to generate hashed value .

I think we can consider using the `random_int` or `random_bytes` to generate default salt value and make CSRF token secure.

And the improved approach is as follows:

- Set salt with `random_int` or `random_bytes` as a default value.
  - And it can also refer [Str::random](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Support/Str.php#L428) to know how to generate a cryptographically secure random string.
- Set session id.
- Using the `hash` to do `sha-256` to generate hashed value.

Once this issue is accepted, I will be happy to work on this :).

**Comment by odan** [comment]
A random salt would change for each request and makes the Token invalid. https://3v4l.org/C05Tb

**Comment by peter279k** [comment]
I think it should not call `random_bytes` for every request and it should call once then store random string to be a salt.

And it can generate salt on constructor method.

**Comment by odan** [comment]
I also would like to make the CsrfMiddleware more container "friendly" because the session should not be already startet within the container definiton. So we should remove the $sessionId from the constructor and add `$salt` parameter as required parameter to the constructor.

The new constructor for the IoC container:

```php
public function __construct(StreamFactoryInterface $streamFactory, string $salt)
{
        $this->streamFactory = $streamFactory;
        $this->setSalt($salt);
}
```
